[build]
  command = "yarn run build:js"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "9.5.0"
    NPM_VERSION = "5.6.0"
    YARN_VERSION = "1.3.2"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"